// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/basic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_proto_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_proto_basic_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonRequest) Reset() {
	*x = PersonRequest{}
	mi := &file_proto_basic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRequest) ProtoMessage() {}

func (x *PersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRequest.ProtoReflect.Descriptor instead.
func (*PersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_basic_proto_rawDescGZIP(), []int{1}
}

func (x *PersonRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_basic_proto protoreflect.FileDescriptor

const file_proto_basic_proto_rawDesc = "" +
	"\n" +
	"\x11proto/basic.proto\"B\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x1f\n" +
	"\rPersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id25\n" +
	"\rPersonService\x12$\n" +
	"\tGetPerson\x12\x0e.PersonRequest\x1a\a.PersonB/Z-github.com/thapakazi/learn-grpc/backend/protob\x06proto3"

var (
	file_proto_basic_proto_rawDescOnce sync.Once
	file_proto_basic_proto_rawDescData []byte
)

func file_proto_basic_proto_rawDescGZIP() []byte {
	file_proto_basic_proto_rawDescOnce.Do(func() {
		file_proto_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_basic_proto_rawDesc), len(file_proto_basic_proto_rawDesc)))
	})
	return file_proto_basic_proto_rawDescData
}

var file_proto_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_basic_proto_goTypes = []any{
	(*Person)(nil),        // 0: Person
	(*PersonRequest)(nil), // 1: PersonRequest
}
var file_proto_basic_proto_depIdxs = []int32{
	1, // 0: PersonService.GetPerson:input_type -> PersonRequest
	0, // 1: PersonService.GetPerson:output_type -> Person
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_basic_proto_init() }
func file_proto_basic_proto_init() {
	if File_proto_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_basic_proto_rawDesc), len(file_proto_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_basic_proto_goTypes,
		DependencyIndexes: file_proto_basic_proto_depIdxs,
		MessageInfos:      file_proto_basic_proto_msgTypes,
	}.Build()
	File_proto_basic_proto = out.File
	file_proto_basic_proto_goTypes = nil
	file_proto_basic_proto_depIdxs = nil
}
